import type { FormResult, PowerRankingRow } from "@/datatypes"

export const POWER_RANKING_PAGE_SIZES = [10, 20, 32] as const

export const TOP_POWER_RANK_THRESHOLD = 3

/** Teams ranked in the top tier (1–3) for power-ranking highlight */
export function isTopPowerRank(rank: number): boolean {
  return rank >= 1 && rank <= TOP_POWER_RANK_THRESHOLD
}

/** Elo points deducted per yellow card in tournament discipline adjustment */
export const ELO_YELLOW_CARD_PENALTY = 2

/** Elo points deducted per red card in tournament discipline adjustment */
export const ELO_RED_CARD_PENALTY = 8

export const powerRankingRows: PowerRankingRow[] = [
  {
    id: "arg",
    rank: 1,
    rankChange: 0,
    team: "Argentina",
    code: "ARG",
    confederation: "CONMEBOL",
    group: "A",
    baseElo: 1880,
    played: 3,
    wins: 3,
    draws: 0,
    losses: 0,
    goalsScored: 10,
    goalsAgainst: 3,
    goalDifference: 7,
    xgFor: 6.8,
    yellowCards: 4,
    redCards: 0,
    form: ["W", "W", "D", "W", "W"],
  },
  {
    id: "fra",
    rank: 2,
    rankChange: 1,
    team: "France",
    code: "FRA",
    confederation: "UEFA",
    group: "C",
    baseElo: 1866,
    played: 3,
    wins: 2,
    draws: 0,
    losses: 1,
    goalsScored: 7,
    goalsAgainst: 4,
    goalDifference: 3,
    xgFor: 5.9,
    yellowCards: 6,
    redCards: 0,
    form: ["W", "L", "W", "W", "D"],
  },
  {
    id: "eng",
    rank: 3,
    rankChange: -1,
    team: "England",
    code: "ENG",
    confederation: "UEFA",
    group: "B",
    baseElo: 1853,
    played: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsScored: 8,
    goalsAgainst: 3,
    goalDifference: 5,
    xgFor: 5.2,
    yellowCards: 3,
    redCards: 0,
    form: ["W", "D", "W", "W", "L"],
  },
  {
    id: "bra",
    rank: 4,
    rankChange: 2,
    team: "Brazil",
    code: "BRA",
    confederation: "CONMEBOL",
    group: "G",
    baseElo: 1851,
    played: 3,
    wins: 2,
    draws: 0,
    losses: 1,
    goalsScored: 6,
    goalsAgainst: 4,
    goalDifference: 2,
    xgFor: 5.7,
    yellowCards: 5,
    redCards: 1,
    form: ["W", "L", "W", "D", "W"],
  },
  {
    id: "esp",
    rank: 5,
    rankChange: 0,
    team: "Spain",
    code: "ESP",
    confederation: "UEFA",
    group: "D",
    baseElo: 1836,
    played: 3,
    wins: 1,
    draws: 2,
    losses: 0,
    goalsScored: 8,
    goalsAgainst: 4,
    goalDifference: 4,
    xgFor: 6.1,
    yellowCards: 7,
    redCards: 0,
    form: ["D", "W", "D", "W", "W"],
  },
  {
    id: "ger",
    rank: 6,
    rankChange: 3,
    team: "Germany",
    code: "GER",
    confederation: "UEFA",
    group: "L",
    baseElo: 1835,
    played: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsScored: 7,
    goalsAgainst: 3,
    goalDifference: 4,
    xgFor: 5.4,
    yellowCards: 4,
    redCards: 0,
    form: ["W", "D", "W", "L", "W"],
  },
  {
    id: "por",
    rank: 7,
    rankChange: -2,
    team: "Portugal",
    code: "POR",
    confederation: "UEFA",
    group: "H",
    baseElo: 1828,
    played: 3,
    wins: 2,
    draws: 0,
    losses: 1,
    goalsScored: 6,
    goalsAgainst: 4,
    goalDifference: 2,
    xgFor: 4.8,
    yellowCards: 8,
    redCards: 0,
    form: ["W", "L", "W", "D", "W"],
  },
  {
    id: "ned",
    rank: 8,
    rankChange: 0,
    team: "Netherlands",
    code: "NED",
    confederation: "UEFA",
    group: "F",
    baseElo: 1816,
    played: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsScored: 7,
    goalsAgainst: 3,
    goalDifference: 4,
    xgFor: 5.0,
    yellowCards: 5,
    redCards: 0,
    form: ["W", "D", "W", "W", "L"],
  },
  {
    id: "col",
    rank: 9,
    rankChange: 4,
    team: "Colombia",
    code: "COL",
    confederation: "CONMEBOL",
    group: "I",
    baseElo: 1812,
    played: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsScored: 6,
    goalsAgainst: 2,
    goalDifference: 4,
    xgFor: 4.6,
    yellowCards: 9,
    redCards: 0,
    form: ["W", "D", "W", "W", "D"],
  },
  {
    id: "mar",
    rank: 10,
    rankChange: 1,
    team: "Morocco",
    code: "MAR",
    confederation: "CAF",
    group: "E",
    baseElo: 1804,
    played: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsScored: 5,
    goalsAgainst: 2,
    goalDifference: 3,
    xgFor: 4.2,
    yellowCards: 6,
    redCards: 0,
    form: ["W", "D", "W", "L", "W"],
  },
  {
    id: "usa",
    rank: 11,
    rankChange: -3,
    team: "United States",
    code: "USA",
    confederation: "CONCACAF",
    group: "B",
    baseElo: 1791,
    played: 3,
    wins: 1,
    draws: 2,
    losses: 0,
    goalsScored: 4,
    goalsAgainst: 3,
    goalDifference: 1,
    xgFor: 4.1,
    yellowCards: 7,
    redCards: 0,
    form: ["D", "W", "D", "L", "W"],
  },
  {
    id: "jpn",
    rank: 12,
    rankChange: 2,
    team: "Japan",
    code: "JPN",
    confederation: "AFC",
    group: "D",
    baseElo: 1787,
    played: 3,
    wins: 2,
    draws: 0,
    losses: 1,
    goalsScored: 5,
    goalsAgainst: 4,
    goalDifference: 1,
    xgFor: 3.9,
    yellowCards: 4,
    redCards: 0,
    form: ["W", "L", "W", "D", "W"],
  },
  {
    id: "mex",
    rank: 13,
    rankChange: -1,
    team: "Mexico",
    code: "MEX",
    confederation: "CONCACAF",
    group: "A",
    baseElo: 1776,
    played: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    goalsScored: 4,
    goalsAgainst: 5,
    goalDifference: -1,
    xgFor: 3.5,
    yellowCards: 10,
    redCards: 1,
    form: ["W", "D", "L", "W", "L"],
  },
  {
    id: "kor",
    rank: 14,
    rankChange: 0,
    team: "South Korea",
    code: "KOR",
    confederation: "AFC",
    group: "H",
    baseElo: 1768,
    played: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    goalsScored: 4,
    goalsAgainst: 4,
    goalDifference: 0,
    xgFor: 3.8,
    yellowCards: 5,
    redCards: 0,
    form: ["D", "W", "L", "D", "W"],
  },
  {
    id: "sui",
    rank: 15,
    rankChange: -2,
    team: "Switzerland",
    code: "SUI",
    confederation: "UEFA",
    group: "G",
    baseElo: 1763,
    played: 3,
    wins: 1,
    draws: 2,
    losses: 0,
    goalsScored: 4,
    goalsAgainst: 3,
    goalDifference: 1,
    xgFor: 3.4,
    yellowCards: 6,
    redCards: 0,
    form: ["D", "W", "D", "L", "D"],
  },
  {
    id: "aus",
    rank: 16,
    rankChange: 1,
    team: "Australia",
    code: "AUS",
    confederation: "AFC",
    group: "C",
    baseElo: 1757,
    played: 3,
    wins: 2,
    draws: 0,
    losses: 1,
    goalsScored: 4,
    goalsAgainst: 3,
    goalDifference: 1,
    xgFor: 3.2,
    yellowCards: 8,
    redCards: 0,
    form: ["W", "L", "W", "D", "L"],
  },
  {
    id: "cro",
    rank: 17,
    rankChange: 0,
    team: "Croatia",
    code: "CRO",
    confederation: "UEFA",
    group: "E",
    baseElo: 1746,
    played: 3,
    wins: 1,
    draws: 2,
    losses: 0,
    goalsScored: 6,
    goalsAgainst: 3,
    goalDifference: 3,
    xgFor: 3.6,
    yellowCards: 5,
    redCards: 0,
    form: ["D", "W", "D", "W", "L"],
  },
  {
    id: "sen",
    rank: 18,
    rankChange: 2,
    team: "Senegal",
    code: "SEN",
    confederation: "CAF",
    group: "F",
    baseElo: 1742,
    played: 3,
    wins: 2,
    draws: 0,
    losses: 1,
    goalsScored: 4,
    goalsAgainst: 3,
    goalDifference: 1,
    xgFor: 3.1,
    yellowCards: 7,
    redCards: 0,
    form: ["W", "L", "W", "W", "D"],
  },
  {
    id: "uru",
    rank: 19,
    rankChange: -4,
    team: "Uruguay",
    code: "URU",
    confederation: "CONMEBOL",
    group: "H",
    baseElo: 1744,
    played: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    goalsScored: 4,
    goalsAgainst: 4,
    goalDifference: 0,
    xgFor: 3.3,
    yellowCards: 11,
    redCards: 1,
    form: ["D", "W", "L", "L", "W"],
  },
  {
    id: "bel",
    rank: 20,
    rankChange: -1,
    team: "Belgium",
    code: "BEL",
    confederation: "UEFA",
    group: "K",
    baseElo: 1737,
    played: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsScored: 6,
    goalsAgainst: 3,
    goalDifference: 3,
    xgFor: 4.0,
    yellowCards: 4,
    redCards: 0,
    form: ["W", "D", "W", "L", "D"],
  },
]

export function getDisciplineEloPenalty(
  row: Pick<PowerRankingRow, "yellowCards" | "redCards">
): number {
  return (
    row.yellowCards * ELO_YELLOW_CARD_PENALTY +
    row.redCards * ELO_RED_CARD_PENALTY
  )
}

export function getAdjustedElo(row: PowerRankingRow): number {
  return row.baseElo - getDisciplineEloPenalty(row)
}

export function formatGoalDifference(value: number): string {
  return value > 0 ? `+${value}` : String(value)
}

export function formatXg(value: number): string {
  return value.toFixed(1)
}

export function formatRankChange(change: number): string {
  if (change > 0) {
    return `+${change}`
  }

  if (change < 0) {
    return String(change)
  }

  return "—"
}

export function formatFormLabel(form: FormResult[]): string {
  return form
    .map((result) => {
      if (result === "W") {
        return "Win"
      }

      if (result === "D") {
        return "Draw"
      }

      return "Loss"
    })
    .join(", ")
}

export function filterPowerRankingsByConfederation(
  rows: PowerRankingRow[],
  confederation: string
): PowerRankingRow[] {
  if (confederation === "all") {
    return rows
  }

  return rows.filter((row) => row.confederation === confederation)
}
