"""add_image_url_to_players

Revision ID: 0f469d92e454
Revises: d23456789012
Create Date: 2026-06-05 12:56:35.273667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f469d92e454'
down_revision = 'd23456789012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('players')]
    
    if 'image_url' not in columns:
        op.add_column('players', sa.Column('image_url', sa.String(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_players_stats_rating', 'players', [sa.literal_column("((stats_json ->> 'rating'::text)::double precision)")], unique=False)
    op.drop_column('players', 'image_url')
    # ### end Alembic commands ###
