"""add_indexes_for_sorting_and_filtering_v2

Revision ID: 738efcc7d62d
Revises: e1d4a8f7c221
Create Date: 2026-06-02 19:13:10.853840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '738efcc7d62d'
down_revision = 'e1d4a8f7c221'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_matches_kickoff_utc'), 'matches', ['kickoff_utc'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.add_column('players', sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('players', 'club_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_players_rating'), 'players', ['rating'], unique=False)
    op.create_index(op.f('ix_teams_group'), 'teams', ['group'], unique=False)
    op.create_index(op.f('ix_teams_players_indexed'), 'teams', ['players_indexed'], unique=False)
    op.create_index(op.f('ix_teams_points'), 'teams', ['points'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_points'), table_name='teams')
    op.drop_index(op.f('ix_teams_players_indexed'), table_name='teams')
    op.drop_index(op.f('ix_teams_group'), table_name='teams')
    op.drop_index(op.f('ix_players_rating'), table_name='players')
    op.alter_column('players', 'club_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('players', 'stats_json')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_kickoff_utc'), table_name='matches')
    # ### end Alembic commands ###
