"""Added columns for team

Revision ID: 7461041c429e
Revises: 760044df3e07
Create Date: 2026-05-25 01:44:23.590422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7461041c429e'
down_revision = '760044df3e07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # Update players table
    if 'players' in tables:
        players_columns = [col['name'] for col in inspector.get_columns('players')]
        if 'country_code' in players_columns:
            op.alter_column('players', 'country_code',
                       existing_type=sa.VARCHAR(length=10),
                       type_=sa.String(length=3),
                       existing_nullable=True)
            
            players_indexes = [idx['name'] for idx in inspector.get_indexes('players')]
            if 'ix_players_country_code' not in players_indexes:
                op.create_index(op.f('ix_players_country_code'), 'players', ['country_code'], unique=False)
            
            try:
                op.create_foreign_key(None, 'players', 'teams', ['country_code'], ['code'])
            except Exception:
                pass

    # Add columns to teams
    if 'teams' in tables:
        teams_columns = [col['name'] for col in inspector.get_columns('teams')]
        columns_to_add = [
            ('goals_for', sa.SmallInteger(), None),
            ('goals_against', sa.SmallInteger(), None),
            ('position', sa.SmallInteger(), None),
            ('points', sa.SmallInteger(), '0'),
            ('matches_played', sa.SmallInteger(), '0'),
            ('matches_won', sa.SmallInteger(), '0'),
            ('matches_drawn', sa.SmallInteger(), '0'),
            ('matches_lost', sa.SmallInteger(), '0'),
            ('players_indexed', sa.Boolean(), 'false'),
        ]
        
        for col_name, col_type, server_default in columns_to_add:
            if col_name not in teams_columns:
                kwargs = {'server_default': server_default} if server_default else {}
                op.add_column('teams', sa.Column(col_name, col_type, nullable=True, **kwargs))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'players_indexed')
    op.drop_column('teams', 'matches_lost')
    op.drop_column('teams', 'matches_drawn')
    op.drop_column('teams', 'matches_won')
    op.drop_column('teams', 'matches_played')
    op.drop_column('teams', 'points')
    op.drop_column('teams', 'position')
    op.drop_column('teams', 'goals_against')
    op.drop_column('teams', 'goals_for')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_index(op.f('ix_players_country_code'), table_name='players')
    op.alter_column('players', 'country_code',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
