"""Added columns for team

Revision ID: 7461041c429e
Revises: 760044df3e07
Create Date: 2026-05-25 01:44:23.590422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7461041c429e'
down_revision = '760044df3e07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update players table
    op.alter_column('players', 'country_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=True)
    op.create_index(op.f('ix_players_country_code'), 'players', ['country_code'], unique=True)
    op.create_foreign_key(None, 'players', 'teams', ['country_code'], ['code'])

    # Add columns to teams
    op.add_column('teams', sa.Column('goals_for', sa.SmallInteger(), nullable=True))
    # Note: Setting default=0 in model but migration needs server_default or manual update if desired.
    # For now we just add columns.
    op.add_column('teams', sa.Column('goals_against', sa.SmallInteger(), nullable=True))
    op.add_column('teams', sa.Column('position', sa.SmallInteger(), nullable=True))
    # We use server_default='0' for consistency with the model defaults if they were intended.
    op.add_column('teams', sa.Column('points', sa.SmallInteger(), server_default='0', nullable=True))
    op.add_column('teams', sa.Column('matches_played', sa.SmallInteger(), server_default='0', nullable=True))
    op.add_column('teams', sa.Column('matches_won', sa.SmallInteger(), server_default='0', nullable=True))
    op.add_column('teams', sa.Column('matches_drawn', sa.SmallInteger(), server_default='0', nullable=True))
    op.add_column('teams', sa.Column('matches_lost', sa.SmallInteger(), server_default='0', nullable=True))
    op.add_column('teams', sa.Column('players_indexed', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'players_indexed')
    op.drop_column('teams', 'matches_lost')
    op.drop_column('teams', 'matches_drawn')
    op.drop_column('teams', 'matches_won')
    op.drop_column('teams', 'matches_played')
    op.drop_column('teams', 'points')
    op.drop_column('teams', 'position')
    op.drop_column('teams', 'goals_against')
    op.drop_column('teams', 'goals_for')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_index(op.f('ix_players_country_code'), table_name='players')
    op.alter_column('players', 'country_code',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
