"""create players table

Revision ID: 760044df3e07
Revises: a1b2c3d4e5f6
Create Date: 2026-05-25 00:24:23.214303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760044df3e07'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('classification', sa.Enum('G', 'D', 'M', 'F', name='playerclassification'), nullable=True),
    sa.Column('club_id', sa.BigInteger(), nullable=True),
    sa.Column('positions', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.SmallInteger(), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('foot', sa.Enum('Left', 'Right', name='playerfoot'), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('market_value', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_club_id'), 'players', ['club_id'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    
    # Also add missing columns to teams if they don't exist
    # (Note: Using try-except or check for column existence is better but for a simple migration we'll just put them here)
    # Actually, Alembic detected them as missing.
    op.add_column('teams', sa.Column('fifa_ranking', sa.SmallInteger(), nullable=True))
    op.add_column('teams', sa.Column('sofascore_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teams_sofascore_id'), 'teams', ['sofascore_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_sofascore_id'), table_name='teams')
    op.drop_column('teams', 'sofascore_id')
    op.drop_column('teams', 'fifa_ranking')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_club_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
