"""create players table

Revision ID: 760044df3e07
Revises: a1b2c3d4e5f6
Create Date: 2026-05-25 00:24:23.214303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760044df3e07'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'players' not in tables:
        op.create_table('players',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.Column('classification', sa.Enum('G', 'D', 'M', 'F', name='playerclassification'), nullable=True),
        sa.Column('club_id', sa.BigInteger(), nullable=True),
        sa.Column('positions', sa.String(), nullable=True),
        sa.Column('weight_kg', sa.SmallInteger(), nullable=True),
        sa.Column('height_cm', sa.SmallInteger(), nullable=True),
        sa.Column('foot', sa.Enum('Left', 'Right', name='playerfoot'), nullable=True),
        sa.Column('country_code', sa.String(length=10), nullable=True),
        sa.Column('market_value', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Refresh tables list
    tables = inspector.get_table_names()
    players_indexes = []
    if 'players' in tables:
        players_indexes = [idx['name'] for idx in inspector.get_indexes('players')]

    if 'ix_players_club_id' not in players_indexes:
        op.create_index(op.f('ix_players_club_id'), 'players', ['club_id'], unique=False)
    if 'ix_players_id' not in players_indexes:
        op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    if 'ix_players_name' not in players_indexes:
        op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    
    # Handle teams columns
    if 'teams' in tables:
        teams_columns = [col['name'] for col in inspector.get_columns('teams')]
        if 'fifa_ranking' not in teams_columns:
            op.add_column('teams', sa.Column('fifa_ranking', sa.SmallInteger(), nullable=True))
        if 'sofascore_id' not in teams_columns:
            op.add_column('teams', sa.Column('sofascore_id', sa.Integer(), nullable=True))
        
        teams_indexes = [idx['name'] for idx in inspector.get_indexes('teams')]
        if 'ix_teams_sofascore_id' not in teams_indexes:
            op.create_index(op.f('ix_teams_sofascore_id'), 'teams', ['sofascore_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_sofascore_id'), table_name='teams')
    op.drop_column('teams', 'sofascore_id')
    op.drop_column('teams', 'fifa_ranking')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_club_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
