"""Initial migration

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2026-05-22 21:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'teams' not in tables:
        op.create_table('teams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('code', sa.String(), nullable=True),
        sa.Column('logo_url', sa.String(), nullable=True),
        sa.Column('group', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Refresh tables list
    tables = inspector.get_table_names()
    if 'teams' in tables:
        teams_columns = [col['name'] for col in inspector.get_columns('teams')]
        teams_indexes = [idx['name'] for idx in inspector.get_indexes('teams')]

        if 'ix_teams_code' not in teams_indexes and 'code' in teams_columns:
            op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=True)
        if 'ix_teams_id' not in teams_indexes and 'id' in teams_columns:
            op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
        if 'ix_teams_name' not in teams_indexes and 'name' in teams_columns:
            op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    
    if 'matches' not in tables:
        op.create_table('matches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('round', sa.String(), nullable=True),
        sa.Column('group', sa.String(), nullable=True),
        sa.Column('home_team_code', sa.String(), nullable=True),
        sa.Column('away_team_code', sa.String(), nullable=True),
        sa.Column('stadium', sa.String(), nullable=True),
        sa.Column('kickoff_utc', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('phase', sa.String(), nullable=True),
        sa.Column('home_score', sa.Integer(), nullable=True),
        sa.Column('away_score', sa.Integer(), nullable=True),
        sa.Column('home_pen', sa.Integer(), nullable=True),
        sa.Column('away_pen', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['away_team_code'], ['teams.code'], ),
        sa.ForeignKeyConstraint(['home_team_code'], ['teams.code'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Refresh tables list
    tables = inspector.get_table_names()
    if 'matches' in tables:
        matches_columns = [col['name'] for col in inspector.get_columns('matches')]
        matches_indexes = [idx['name'] for idx in inspector.get_indexes('matches')]
    
        if 'ix_matches_id' not in matches_indexes and 'id' in matches_columns:
            op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_code'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
